import dotenv from "dotenv";
dotenv.config();

const PORT = process.env.PORT
const MONGO_URI = process.env.MONGO_URI
const SALT = process.env.PORT
const JWT_SECRET_KEY = process.env.JWT_SECRET_KEY
const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET
const CLOUDINARY_DISTRIBUTION = process.env.CLOUDINARY_DISTRIBUTION
const CLOUDINARY_PREFIX = process.env.CLOUDINARY_PREFIX

export {
    PORT,
    MONGO_URI,
    SALT,
    JWT_SECRET_KEY,
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
    CLOUDINARY_DISTRIBUTION,
    CLOUDINARY_PREFIX
};